#!/bin/sh

PREFIX=http://khedin.starlink.ru:8000/

URL=$1 
shift

if echo $URL | grep '^http://' >/dev/null; then
	PREFIX=''
fi

n=10
N=100
T=50

echo >&2 "Running $n times, $N reqs / $T threads: $PREFIX/$URL"

for i in `seq $n`; do 
	sudo ab -c $T -n $N "$PREFIX/$URL" 
	sleep 0.3
done | grep '^Time taken for tests:' | dispersion

