#!/bin/sh

set -e

if [ -z "$1" ] || [ ! -r "$1" ]; then
  echo "Usage: $0 <file> [options]..."
  echo "Commit file with --date set to last modification date"
  exit 1
fi

set -x

FILE=$1
shift

git add "$FILE"
git commit --date="$(stat -c %y "$FILE")" $FILE "$@"

