#!/usr/bin/perl -w

use strict;

my $k;

if ($ARGV[0] eq '-n') {
	shift;
	$k = shift;
};

my $n = 0+@ARGV ;

$|=1;

my $i = dice ($n);
while ((!defined $k) || $k-->0) {
	$i += dice ($n - 1);
	$i %= $n;
	print $ARGV[$i],"\n";
};

sub dice {
	return 1 + int (rand() * shift);
};