#!/bin/sh

if /sbin/ifconfig ppp0 2>/dev/null; then
	echo "PPP already started"
else
	/usr/sbin/pppd call starlink  $*
fi

#if [ "$1" = hup ]; then 
#	while :; do
#		/usr/sbin/pppd call starlink 
#		sleep 10;
#	done
#else 
#	cd /tmp
#	nohup -- $0 hup >$USER-vpn.out 2>&1 &
#fi

