#!/bin/sh

FROM=CP1251
TO=UTF-8

function usage () {
	echo "Usage: " `basename $0` "[--from <charset>] [--to <charset] [--] files ..."
	exit 1
}

if test -z "$1"; then 
	usage
fi

while [ "x${1:0:2}" == "x--" ]; do
# 	echo "$1"
	case $1 in 
	--from|-f)
		shift
		FROM="$1"
		shift
	;;
	
	--to|-t)
		shift
		TO="$1"
		shift
	;;
	--) 
		shift
		break
	;;
	
	*)  
		echo "Unknown option $1"
		usage
	;;
	esac
done

yes n | for i in "$@"; do
	# converts to current locale
	test -f "$i" &&\
	iconv -f "$FROM" -t "$TO" -c -- "$i" >"$i.$TO" &&\
		mv -i "$i" "$i.orig" &&\
		mv -i "$i.$TO" "$i"
done 

